ROOTCFLAGS   	:= $(shell root-config --cflags)
ROOTLIBS   =  -L$(shell root-config --libdir) -lCore -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lpthread -lSpectrum -lGeomBuilder -lGenVector -lGeom -lRGL

CXX        = $(GXX)

PSQL_CFLAGS=	-DUSE_PSQL_DB -I/usr/include/postgresql
PSQL_LIBS  = 	-lpq 

DLOPEN_PAM=0

ifeq ($(DLOPEN_PAM),1)
        LIBPAM=-ldl
else
        LIBPAM=-lpam
endif

DEFS		=  -DLINUX -Wall -Wno-unused -fexceptions -D_REENTRANT 
#-DDEBUG_TRACES


CXX_ATHLON_FLAGS = -march=athlon-tbird -pipe \
		   -ffast-math -fomit-frame-pointer

CXX_XEON_FLAGS = -march=x86-64 -pipe \
		 -ffast-math -fomit-frame-pointer

CXX_OPTERON_FLAGS = -march=opteron -pipe \
		    -ffast-math -fomit-frame-pointer


CXXFLAGS     =  -O3 -g -Wall -m64 -std=gnu++0x $(ROOTCFLAGS)
CXXFLAGS     += $(ROOTCFLAGS) 
CXXFLAGS     += -I$(INCLUDE_DAQ)
CXXFLAGS     += -I$(INCLUDE_PERSO)
CXXFLAGS     += -I$(MIMACTOOLS_PATH)/MimacObjectAnalysis/include
CXXFLAGS     += -I$(MIMACTOOLS_PATH)/DataMimacTools/include
CXXFLAGS     += -I$(MIMACTOOLS_PATH)/TEventFileAccess
CXXFLAGS     += -I../acquisition/daq/MimacDaqDataBaseConnection
CXXFLAGS     += -I../acquisition/daqCommonParts
CXXFLAGS     += -I../acquisition/sensor/genIDL
CXXFLAGS     += -I.././acquisition/daq
CXXFLAGS     += -I.././acquisition/daqCommonParts/SortListType
CXXFLAGS     += -I.././acquisition/daqCommonParts/PostgresqlConnection
CXXFLAGS     += -I.././acquisition/daqCommonParts/LogRecorder/
CXXFLAGS     += -I/usr/local/include/glibmm-2.4
CXXFLAGS     += -I /usr/local/include/glibmm-2.4/glibmm
CXXFLAGS     += -I/usr/local/lib/glibmm-2.4/include
CXXFLAGS     += -I/usr/local/include/glib-2.0
CXXFLAGS     += -I/usr/local/lib/glib-2.0/include
CXXFLAGS     += -I/usr/local/include/sigc++-2.0
CXXFLAGS     += -I/usr/include


LIBS            =  -stdlib=libc++  -lpthread $(ROOTLIBS) $(SYSLIBS) 
LIBS 		+= -L$(MIMACTOOLS_PATH)/lib -lMimacTools
LIBS            += -L/usr/local/lib -lboost_regex  -lmysqlclient

EXEC_OBJS 	= obj/MimacDaqDataBaseConnection.o

SRC = $(wildcard *.cpp)
OBJ = $(SRC:.cpp=.o)
EXE = $(SRC:.cpp=.bin)


all : $(EXE)

obj/%.o : %.cpp $(EXEC_OBJS)
	@echo "-> Building object : " $@
	$(CXX) $(CXXFLAGS) $(PSQL_CFLAGS) -fPIC  -o $@  -c $<

obj/%.o: /Users/riffard/These/MimacTools/acquisition/daq/MimacDaqDataBaseConnection/%.cc
	$(CXX) -c $< -o $@ $(CXXFLAGS) $(CPPFLAGS) $(DEFS) $(PSQL_CFLAGS) 

%.bin : obj/%.o $(EXEC_OBJS)
	@echo "-> Building : " $@
	$(CXX) -stdlib=libstdc++ ${LIBS} $(PSQL_LIBS) $(PCAP_LIBS) $(EXEC_OBJS) -o $@ $< $(OBJSRC) 

clean :
	@rm -f obj/*.o
	@rm -f *.bin
